paidcommand:
  #是否开启付费指令功能
  enable: true
  #货币名
  coin: "金币"
  point: "点券"
language:
  # 变量：${MONEY}为指令所需支付的“金币”
  #       ${NOW}为玩家拥有的“金币”
  coin:
    #金钱不足
    notEnough: "[PaidCommand] > §a§b金币不足，指令售价${MONEY}枚金币，您的金币：${NOW}"
    #成功购买使用指令
    success: "[PaidCommand] > §b成功使用指令，花费${MONEY}枚金币，你现有金币：${NOW}枚"
  point:
    #点券不足
    notEnough: "[PaidCommand] > §a§b点券不足，指令售价${MONEY}个点券，您的点券：${NOW}"
    #成功购买使用指令
    success: "[PaidCommand] > §b成功使用指令，花费${MONEY}枚点券，你现有点券：${NOW}枚"
